spring:
  datasource:
    name: rtdsDS
    url: jdbc:oracle:thin:@localhost:1521/orcl1pdb1
    username: username
    password: PWD
    driver-class-name: oracle.jdbc.OracleDriver
    maximumPoolSize: 50
    minimumIdle: 5
    poolName: POOL_MUTABLE